import { enLang, ruLang } from './ls-load-save';

export const localizationObj = {
  [ruLang]: {
    signIn: 'Вход',
    signUp: 'Регистрация',
    signOut: 'Выход',
    language: 'Язык',
    meetOurTeam: 'НАША КОМАНДА',
    login: 'Логин',
    password: 'Пароль',
    name: 'Имя',
    repeatPassword: 'Повтори пароль',
    editUser: 'Редактировать пользователя',
    changePassword: 'Сменить пароль',
    deleteUser: 'Удалить пользователя',
    oldPassword: 'Старый пароль',
    newPassword: 'Новый пароль',
    enterYourPassword: 'Введи свой пароль',
    enterYourLogin: 'Введи свой логин',
    enterYourName: 'Введи свое имя',
    emptyField: 'Пустое поле',
    onlyNumbersLetters: 'Только цифры и латинские буквы',
    lessThanFour: ' не может быть короче 4 символов',
    passwordsMatch: 'Пароли не совпадают',
    createBoard: 'Создать доску',
    createColumn: 'Добавить новую колонку',
    createTask: 'Создать задачу',
    yourBoards: 'Твои доски',
    board: 'Доска',
    boards: 'Доски',
    back: 'Назад',
    submit: 'Подтвердить',
    cancel: 'Отмена',
    doYouWantToDelete: 'Вы хотите удалить',
    areYouSure: 'Вы уверены?',
    error: 'Ошибка!',
    success: 'Успех!',
    updateSuccessful: 'обновлен успешно!',
    user: 'Пользователь',
    wrongPassword: 'Неверный пароль',
    afterDeleteRedirect:
      'После удаления пользователя вы будете перенаправлены на главную страницу!',
    update: 'Обновить',
    loading: 'Загрузка...',
    addATitle: 'Добавить заголовок',
    yourTask: 'Твоя задача',
    shatau: 'ЕВГЕНИЙ ШАТОВ',
    kochieva: 'ВИКТОРИЯ КОЧИЕВА',
    karakulka: 'ДМИТРИЙ КАРАКУЛЬКО',
  },
  [enLang]: {
    signIn: 'Sign In',
    signUp: 'Sign Up',
    signOut: 'Sign Out',
    language: 'Language',
    meetOurTeam: 'MEET OUR TEAM',
    login: 'Login',
    password: 'Password',
    name: 'Name',
    repeatPassword: 'Repeat you password',
    editUser: 'Edit user',
    changePassword: 'Change password',
    deleteUser: 'Delete user',
    oldPassword: 'Old password',
    newPassword: 'New password',
    enterYourPassword: 'Enter your password',
    enterYourLogin: 'Enter your login',
    enterYourName: 'Enter your name',
    emptyField: 'Empty field!',
    onlyNumbersLetters: 'Only numbers and english letters',
    lessThanFour: ' can not be less than 4 symbols',
    passwordsMatch: 'Passwords do not match',
    createBoard: 'Create a new board',
    createColumn: 'New column',
    createTask: 'Add a new task',
    yourBoards: 'Your boards',
    board: 'Board',
    boards: 'Boards',
    back: 'Back',
    submit: 'Submit',
    cancel: 'Cancel',
    doYouWantToDelete: 'Do you want to delete ',
    areYouSure: 'Are you sure?',
    error: 'Error!',
    success: 'Success!',
    updateSuccessful: 'update successful!',
    user: 'User',
    wrongPassword: 'Wrong password',
    afterDeleteRedirect: 'After deletion, you will be redirected to the welcome page!',
    update: 'Update',
    loading: 'Loading...',
    addATitle: 'Add a title',
    yourTask: 'Your task',
    shatau: 'YAUHENI SHATAU',
    kochieva: 'VICTORIA KOCHIEVA',
    karakulka: 'DZMITRY KARAKULKA',
  },
};
