import { enLang, ruLang } from './ls-load-save';

export const localizationObj = {
  [ruLang]: {
    signIn: 'Вход',
    signUp: 'Регистрация',
    signOut: 'Выход',
    language: 'Язык',
    profile: 'Профиль',
    meetOurTeam: 'Наша команда',
    login: 'Логин',
    password: 'Пароль',
    name: 'Имя',
    repeatPassword: 'Повторите пароль',
    editUser: 'Редактировать пользователя',
    changePassword: 'Сменить пароль',
    deleteUser: 'Удалить пользователя',
    oldPassword: 'Старый пароль',
    newPassword: 'Новый пароль',
    enterYourPassword: 'Введите свой пароль',
    enterYourLogin: 'Введите свой логин',
    enterYourName: 'Введите свое имя',
    emptyField: 'Пустое поле',
    onlyNumbersLetters: 'Только цифры и латинские буквы',
    lessThanFour: ' не может быть короче 4 символов',
    passwordsMatch: 'Пароли не совпадают',
    createBoard: 'Создать новую доску',
    createColumn: 'Добавить колонку',
    createTask: 'Добавить задачу',
    yourBoards: 'Ваши доски',
    board: 'Доска',
    boards: 'Доски',
    boardsHeader: 'На главную',
    openBoard: 'Открыть доску',
    back: 'Назад',
    submit: 'Подтвердить',
    cancel: 'Отмена',
    doYouWantToDelete: 'Вы хотите удалить',
    areYouSure: 'Вы уверены?',
    error: 'Ошибка!',
    success: 'Успех!',
    updateSuccessful: 'обновлен успешно!',
    user: 'Пользователь',
    wrongPassword: 'Неверный пароль',
    afterDeleteRedirect:
      'После удаления пользователя вы будете перенаправлены на главную страницу!',
    update: 'Обновить',
    loading: 'Загрузка...',
    addATitle: 'Добавить заголовок',
    addADescription: 'Добавить описание',
    author: 'Пользователь',
    yourTask: 'Задача',
    taskDescription: 'Описание',
    shatau: 'Евгений Шатов',
    kochieva: 'Виктория Кочиева',
    karakulka: 'Дмитрий Каракулько',
    doYouWantToChangeUser: 'Выберите нового пользователя',
    welcome: 'Добро пожаловать',
    app: 'Ваша система управлениями проектами',
    aboutProject:
      'Приложение для управления проектами — это приложение, которое назначает задачи отдельным участникам проекта или группы. Это визуальный инструмент, который позволяет вашей команде управлять любым типом проекта, рабочим процессом или отслеживанием задач. Добавьте файлы, контрольные списки или даже автоматизацию: настройте все так, чтобы ваша команда работала лучше всего. Просто зарегистрируйтесь, создайте доску, и вперед!',
  },
  [enLang]: {
    signIn: 'Sign In',
    signUp: 'Sign Up',
    signOut: 'Sign Out',
    language: 'Language',
    profile: 'Profile',
    meetOurTeam: 'Meet our team',
    login: 'Login',
    password: 'Password',
    name: 'Name',
    repeatPassword: 'Repeat password',
    editUser: 'Edit user',
    changePassword: 'Change password',
    deleteUser: 'Delete user',
    oldPassword: 'Old password',
    newPassword: 'New password',
    enterYourPassword: 'Enter your password',
    enterYourLogin: 'Enter your login',
    enterYourName: 'Enter your name',
    emptyField: 'Empty field!',
    onlyNumbersLetters: 'Only numbers and english letters',
    lessThanFour: ' can not be less than 4 symbols',
    passwordsMatch: 'Passwords do not match',
    createBoard: 'Create a new board',
    createColumn: 'New column',
    createTask: 'Add task',
    yourBoards: 'Your boards',
    board: 'Board',
    boards: 'Boards',
    boardsHeader: 'Main page',
    openBoard: 'Open board',
    back: 'Back',
    submit: 'Submit',
    cancel: 'Cancel',
    doYouWantToDelete: 'Do you want to delete ',
    areYouSure: 'Are you sure?',
    error: 'Error!',
    success: 'Success!',
    updateSuccessful: 'update successful!',
    user: 'User',
    wrongPassword: 'Wrong password',
    afterDeleteRedirect: 'After deletion, you will be redirected to the welcome page!',
    update: 'Update',
    loading: 'Loading...',
    addATitle: 'Add a title',
    addADescription: 'Add a description',
    author: 'User',
    yourTask: 'Task',
    taskDescription: 'Description',
    shatau: 'Yauheni Shatau',
    kochieva: 'Victoria Kochieva',
    karakulka: 'Dzmitry Karakulka',
    doYouWantToChangeUser: 'Choose new task user',
    welcome: 'Welcome',
    app: "It's Your Project Management App",
    aboutProject:
      "Project management app is an application that assigns tasks to individual participants in a project or group. It is the visual tool that empowers your team to manage any type of project, workflow, or task tracking. Add files, checklists, or even automation: Customize it all for how your team works best. Just sign up, create a board, and you're off!",
  },
};
